version: "3.9"
services: 
  express:  
    build: 
      context: ./
      target: development
    image: <%= projectName %>-<%= appName %>-dev
    container_name: <%= projectName %>-<%= appName %>-dev
    ports:
      - '3000:3000'
    volumes:
      <%_if(useTypescript){_%>
      - ./dist:/<%= appName %>/dist
      <%_}else{_%>
      - ./src:/<%= appName %>/src
      <%_}_%>
    environment:
      - NODE_ENV=development
    command: 
      - ./node_modules/.bin/nodemon
      - -L
      <%_if(useTypescript){_%>
      - ./dist/index.js
      <%_}else{_%>
      - ./src/index.js
      <%_}_%>

