version: "3.9"
services: 
  express:  
    build: 
      context: ./
    image: <%= projectName %>-<%= appName %>-prod
    container_name: <%= projectName %>-<%= appName %>-prod
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production

